import { Role, User, Wing, Gender, Cadet } from "@/types";

export const MOCK_USERS: (User | Cadet)[] = [
    {
        id: "ano-1",
        name: "ANO",
        role: Role.ANO,
        regimentalNumber: "NCC/ANO/2024/001",
        pin: "0324",
    },
    {
        id: "suo-1",
        name: "SUO",
        role: Role.SUO,
        regimentalNumber: "AS2020SDIA0300001",
        wing: Wing.ARMY,
        gender: Gender.MALE,
        unitNumber: "30",
        unitName: "Assam BN NCC",
        bloodGroup: "O+",
        enrollmentYear: 2020,
        groupHQ: "Guwahati",
        dte: "North-Eastern Region (NER)",
        pin: "3489",
    },
    {
        id: "suo-2",
        name: "SUO",
        role: Role.SUO,
        regimentalNumber: "AS2020SWIA0300002",
        wing: Wing.ARMY,
        gender: Gender.FEMALE,
        unitNumber: "30",
        unitName: "Assam BN NCC",
        bloodGroup: "A+",
        enrollmentYear: 2020,
        groupHQ: "Guwahati",
        dte: "North-Eastern Region (NER)",
        pin: "3489",
    },
    {
        id: "sgt-1",
        name: "Sgt. Deepjyoti Talkudar",
        role: Role.SGT,
        regimentalNumber: "AS2021SDIA0300003",
        wing: Wing.ARMY,
        gender: Gender.MALE,
        unitNumber: "30",
        unitName: "Assam BN NCC",
        bloodGroup: "B+",
        enrollmentYear: 2021,
        groupHQ: "Guwahati",
        dte: "North-Eastern Region (NER)",
        pin: "5698",
    },
    {
        id: "sgt-2",
        name: "Sgt. Thiyam Bindiya Devi",
        role: Role.SGT,
        regimentalNumber: "AS2021SWIA0300004",
        wing: Wing.ARMY,
        gender: Gender.FEMALE,
        unitNumber: "30",
        unitName: "Assam BN NCC",
        bloodGroup: "O+",
        enrollmentYear: 2021,
        groupHQ: "Guwahati",
        dte: "North-Eastern Region (NER)",
        pin: "5698",
    },
    {
        id: "cdt-1",
        name: "Cdt. Roshni",
        role: Role.CADET,
        regimentalNumber: "AS2022SWIA0300005",
        wing: Wing.ARMY,
        gender: Gender.FEMALE,
        unitNumber: "30",
        unitName: "Assam BN NCC",
        bloodGroup: "AB+",
        enrollmentYear: 2022,
        groupHQ: "Guwahati",
        dte: "North-Eastern Region (NER)",
    },
];

export const MOCK_CLASSES = [
    {
        id: "cls-1",
        title: "Drill Practice - Morning",
        date: "2023-10-25",
        time: "06:00 AM",
        instructorId: "suo-1",
        attendees: [],
    },
    {
        id: "cls-2",
        title: "Weapon Training Theory",
        date: "2023-10-25",
        time: "10:00 AM",
        instructorId: "ano-1",
        attendees: [],
    },
];
