"use client";

import { Button } from "@/components/ui/button";
import { FileText } from "lucide-react";
import { AttendanceRecord, Cadet, ClassSession } from "@/types";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface PdfExportButtonProps {
    classSession?: ClassSession;
    cadets: Cadet[];
    attendance: AttendanceRecord[];
    className?: string;
}

export function PdfExportButton({ classSession, cadets, attendance, className }: PdfExportButtonProps) {
    const handleDownload = () => {
        if (!classSession) return;

        const doc = new jsPDF();

        // Add Header
        doc.setFontSize(18);
        doc.setTextColor(20, 50, 100); // Primary blue
        doc.text("NCC Unit Attendance Report", 14, 20);

        doc.setFontSize(11);
        doc.setTextColor(80, 80, 80);
        doc.text(`Class: ${classSession.title}`, 14, 30);
        doc.text(`Date: ${classSession.date}`, 14, 36);
        doc.text(`Total Strength: ${cadets.length}`, 14, 42);

        // Prepare Table Data
        const tableColumn = ["S.No", "Regimental No", "Rank", "Name", "Unit", "Status"];
        const tableRows: any[] = [];

        let present = 0;
        let absent = 0;
        let late = 0;

        cadets.forEach((cadet, index) => {
            const record = attendance.find(
                r => r.classId === classSession.id && r.cadetId === cadet.id
            );

            const status = record?.status || "NOT MARKED";

            if (status === "PRESENT") present++;
            else if (status === "ABSENT") absent++;
            else if (status === "LATE") late++;

            const statusObj = {
                content: status,
                styles: {
                    textColor: status === "PRESENT" ? [22, 163, 74] :
                        status === "ABSENT" ? [220, 38, 38] :
                            status === "LATE" ? [217, 119, 6] : [100, 100, 100],
                    fontStyle: "bold"
                }
            };

            tableRows.push([
                index + 1,
                cadet.regimentalNumber || "-",
                cadet.rank || "-",
                cadet.name,
                cadet.unitNumber || "-",
                statusObj
            ]);
        });

        // Add Summary Stats
        doc.setFontSize(11);
        doc.text(`Present: ${present}  |  Absent: ${absent}  |  Late: ${late}`, 14, 48);

        // Add Table
        autoTable(doc, {
            head: [tableColumn],
            body: tableRows,
            startY: 54,
            theme: 'grid',
            headStyles: { fillColor: [24, 52, 94], textColor: 255, fontStyle: 'bold' },
            alternateRowStyles: { fillColor: [245, 247, 250] },
            styles: { fontSize: 9, cellPadding: 3 },
            didDrawPage: (data) => {
                // Footer
                const str = "Generated by NCC RGU App - " + new Date().toLocaleString();
                doc.setFontSize(8);
                doc.setTextColor(150);
                const pageSize = doc.internal.pageSize;
                const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
                doc.text(str, data.settings.margin.left, pageHeight - 10);
            }
        });

        doc.save(`Attendance_${classSession.title}_${classSession.date}.pdf`);
    };

    return (
        <Button
            onClick={handleDownload}
            variant="outline"
            className={`flex items-center gap-2 border-red-200/50 text-red-700 hover:bg-red-50 hover:border-red-200 hover:text-red-800 transition-all ${className}`}
            disabled={!classSession}
        >
            <FileText className="w-4 h-4" />
            <span>Export PDF</span>
        </Button>
    );
}
